apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false  # only this pod
description: "This priority class should be used for XYZ service pods only."
